artifact_uri: mlflow-artifacts:/0/7c61b8fb3db445eaaac12319caab4203/artifacts
end_time: 1764494702125
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 7c61b8fb3db445eaaac12319caab4203
run_name: amazing-ray-789
source_name: ''
source_type: 4
source_version: ''
start_time: 1764494697228
status: 3
tags: []
user_id: guts
