artifact_location: mlflow-artifacts:/0/models/m-e93fdbd1b2f3494fb30d92c5b9187ac2/artifacts
creation_timestamp: 1764494858067
experiment_id: '0'
last_updated_timestamp: 1764494862224
model_id: m-e93fdbd1b2f3494fb30d92c5b9187ac2
model_type: ''
name: Random Forest model
source_run_id: 2b25c03a0db04b69adb8f469786b81ee
status: 2
status_message: null
