artifact_uri: mlflow-artifacts:/0/c5c2c8fcee88458cb89ad3ed820d15ad/artifacts
end_time: 1764490476628
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: c5c2c8fcee88458cb89ad3ed820d15ad
run_name: adorable-cub-741
source_name: ''
source_type: 4
source_version: ''
start_time: 1764490476137
status: 3
tags: []
user_id: guts
